### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by Slipehr** [ElectroAAC/electro#43]
Hey, wanted to give this a go for TFS ( https://github.com/otland/forgottenserver ) but seems there are some differences when it comes to creating the database so it's not compatible with TFS.

My setup is as follows:
Docker (Swarm)
Ubuntu 22.04
(also had to manually download newer node.js as it was missing a few modules for Ubuntu when just installing NPM, which also installed an older node.js version (14.xx something))

Since I am using docker, and using internal docker name resolving, there is initially a few issues with a few ts scripts validation on your side, specifically of the host name doesn't accept just "docker_mysql" as host name, but seems to require IP to make this work. I fixed this by doing some work around and disabling this validation, but it's not pretty. This is an issue in the docker world in general, one of the benefits is not having to use static IP's

Initially your SQL schema seems to missing the following tables: (compared to https://github.com/otland/forgottenserver/blob/master/schema.sql)
account_storage
market_history
market_offers
player_inboxitems
player_storeinboxitems

I've gotten **backend** to work with docker as well (not just the mysql db, but also by using node.js docker image directly with ElectroAAC), I just need to initiate the database from inside the docker, and create sample users.

**Comment by WalistonBelles** [comment]
Hi, thanks for testing the project and providing feedback.

Regarding the tables, I will work as soon as possible to add the migrations that are missing, and thus be 100% compatible with the current tfs.

About the problem you faced with docker, I didn't quite understand what the problem is.
